{% set name = 'swat' %}
{% set version = '1.7.0' %}
{% set build = '0' %}

package:
    name: {{ name }}
    version: {{ version }}

source:
    url: https://github.com/sassoftware/python-swat/releases/download/v{{ version }}/python-swat-{{ version }}-linux64.tar.gz  # [linux64]
    url: https://github.com/sassoftware/python-swat/releases/download/v{{ version }}/python-swat-{{ version }}-linux-ppc64le.tar.gz  # [ppc64le]
    url: https://github.com/sassoftware/python-swat/releases/download/v{{ version }}/python-swat-{{ version }}-win64.tar.gz  # [win64]
    url: https://github.com/sassoftware/python-swat/archive/v{{ version }}.tar.gz  # [not linux64 and not win64 and not ppc64le]

build:
    number: {{ build }}
    script: python -m pip install --no-deps --ignore-installed .
    # binary repackaging -- don't do relocation, these are part of manylinux1
    binary_relocation: False
    missing_dso_whitelist:
        - /lib/libpthread.so.0
        - /lib/libm.so.6
        - /lib/libc.so.6
        - /lib/libdl.so.2
        - /lib/libcrypt.so.1
        - /lib/librt.so.1
        - /lib/libresolv.so.2
        - /lib/libgcc_s.so.1
        - /lib/libstdc++.so.6
        - /lib/libXt.so.6  # begin xorgpkg.so
        - /lib/libXmu.so.6  #
        - /lib/libSM.so.6  #
        - /lib/libXext.so.6  #
        - /lib/libjpeg.so.62  #
        - /lib/libICE.so.6  #
        - /lib/libfontconfig.so.1  #
        - /lib/libXft.so.2  #
        - /lib/libpng12.so.0  #
        - /lib/libX11.so.6  # end xorgpkg.so
        - libdfschr-1.4.so
        - libdfssys-1.3.so
        - libdfsfio-1.5.so
        - libdflic-1.4.so
        - libjsig.so
        - libjvm.so
        - /lib/libgssapi_krb5.so.2
        - /lib/libkrb5.so.3
        - /lib/libuuid.so.1
        - /lib64/libnuma.so.1

requirements:
    build:
        - python
        - pip
        - pandas
        - pytz
        - six
        - requests
        - libnuma  # [linux64]
        - libuuid  # [linux64]
        - krb5  # [linux64]
    run:
        - python
        - pandas
        - pytz
        - six
        - requests
        - libnuma  # [linux64]
        - libuuid  # [linux64]
        - krb5  # [linux64]

test:
    imports:
        - swat
    requires:
        - nose
    commands:
        - nosetests -v swat.tests.cas.test_basics:TestBasics.test_summary

about:
    home: https://github.com/sassoftware/python-swat
    license: Apache 2.0 + SAS Additional Functionality
    license_file: LICENSE.md
    summary: SAS Viya Python Client
    doc_url: https://sassoftware.github.io/python-swat/index.html
    dev_url: https://github.com/sassoftware/python-swat
